name: Node.js CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  test:
    name: Run Test Job
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: |
          npm run check > test-results.txt || true

      - name: Upload test results
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: test-results.txt

  deploy:
    name: Deploy Application
    needs: test
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download test results
        uses: actions/download-artifact@v4
        with:
          name: test-results
          path: ./artifacts

      - name: Display test results
        run: cat ./artifacts/test-results.txt

      - name: Install dependencies
        run: npm install

      - name: Deploy using PM2
        run: |
              pm2 delete node-app || true
              pm2 start "npm start" --name="node-app" || true
              pm2 save || true